a=int(input("Enter a number: "))
b=int(input("Enter another number: "))
x=int(input("Enter a third number: "))
print(a&b)
print(a|b)
print(a^b)
print(~a)
print(~b)
print(a<<x)
print(b<<x)
print(a>>x)
print(b>>x)
language=input("Enter your programming language: ")
print("python" in language)
numbers=[1, 2, 3, 4, 5]
print(3 in numbers)
print("6" in numbers)